import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { ArrowRight, LockKeyhole, Mail } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { supabase } from '@/integrations/supabase/client'
import { lovable } from '@/integrations/lovable'
import { Brand } from './shell'
export function AuthPage(){const navigate=useNavigate();const [mode,setMode]=useState<'login'|'forgot'>('login');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user)navigate({to:'/painel',replace:true})})},[navigate]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);try{const email=String(f.get('email'));if(mode==='forgot'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(error)throw error;setMessage('Se o e-mail estiver cadastrado, você receberá o link para redefinir a senha.')}else{const {error}=await supabase.auth.signInWithPassword({email,password:String(f.get('password'))});if(error)throw error;await navigate({to:'/painel',replace:true})}}catch{setMessage(mode==='login'?'Não foi possível entrar. Confira seu e-mail e senha.':'Não foi possível enviar o e-mail. Tente novamente.')}finally{setBusy(false)}}
 async function google(){setBusy(true);setMessage('');try{const r=await lovable.auth.signInWithOAuth('google',{redirect_uri:`${window.location.origin}/auth`});if(r.error)throw r.error;if(!r.redirected)await navigate({to:'/painel',replace:true})}catch{setMessage('Não foi possível entrar com Google. Tente novamente.')}finally{setBusy(false)}}
 return <main className="auth-screen"><div className="auth-top"><Brand/><span className="font-mono text-xs text-muted-foreground">PEOPLE / OPERATIONS</span></div><section className="auth-content"><div className="auth-eyebrow"><span className="status-dot"/> ACESSO AO RH</div><h1>Lions RH<span className="text-primary">.</span></h1><p className="mt-3 mb-9 text-muted-foreground">{mode==='login'?'Bem-vindo de volta. Entre na sua conta.':'Recupere o acesso à sua conta.'}</p><form onSubmit={submit} className="space-y-5"><label className="field-label">E-mail<div className="relative mt-2"><Mail className="input-icon" size={17}/><Input className="pl-10 h-12" name="email" type="email" autoComplete="email" required placeholder="voce@empresa.com.br"/></div></label>{mode==='login'&&<label className="field-label">Senha<div className="relative mt-2"><LockKeyhole className="input-icon" size={17}/><Input className="pl-10 h-12" name="password" type="password" autoComplete="current-password" required placeholder="Sua senha"/></div></label>}{message&&<p role="status" className="text-sm text-primary">{message}</p>}<Button className="w-full h-12" disabled={busy} type="submit">{busy?'Aguarde…':mode==='login'?'Entrar no sistema':'Enviar link'}<ArrowRight/></Button></form>{mode==='login'&&<><div className="auth-divider">ou</div><Button variant="outline" className="w-full h-12" disabled={busy} onClick={google}><span className="font-bold text-lg">G</span> Entrar com Google</Button></>}<Button variant="link" className="mt-5 px-0 text-muted-foreground" onClick={()=>{setMode(mode==='login'?'forgot':'login');setMessage('')}}>{mode==='login'?'Esqueci minha senha':'Voltar para o login'}</Button><p className="mt-6 text-xs text-muted-foreground">Acesso exclusivo para contas autorizadas pelo RH.</p></section><footer className="auth-footer">LIONS RH <span>SEU TIME. EM SINTONIA.</span></footer></main>
}
export function ResetPage(){const [ready,setReady]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const navigate=useNavigate();useEffect(()=>{const recovery=window.location.hash.includes('type=recovery');if(!recovery){setMessage('Link de recuperação inválido. Solicite um novo link.');return}supabase.auth.getUser().then(({data})=>setReady(Boolean(data.user)))},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const password=String(f.get('password'));if(password!==f.get('confirm')){setMessage('As senhas devem ser iguais.');return}setBusy(true);const {error}=await supabase.auth.updateUser({password});setBusy(false);if(error)setMessage('Não foi possível atualizar a senha. Solicite outro link.');else{setMessage('Senha atualizada.');await navigate({to:'/painel',replace:true})}}return <main className="auth-screen"><div className="auth-top"><Brand/></div><section className="auth-content"><h1 className="text-3xl">Nova senha</h1><form className="mt-6 space-y-5" onSubmit={submit}><label className="field-label">Nova senha<Input name="password" type="password" autoComplete="new-password" required minLength={8}/></label><label className="field-label">Confirmar senha<Input name="confirm" type="password" autoComplete="new-password" required minLength={8}/></label>{message&&<p role="status">{message}</p>}<Button type="submit" disabled={!ready||busy}>Salvar senha</Button></form></section></main>}
