import { useState, type FormEvent } from 'react'
import { useServerFn } from '@tanstack/react-start'
import { useQueryClient } from '@tanstack/react-query'
import { Upload, Save } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { supabase } from '@/integrations/supabase/client'
import { fields, sections, money, type Section, type Table } from './config'
import { benefits } from './payroll-report'
import { saveRhRecord, terminateEmployee } from './data.functions'
export type Row = Record<string, unknown> & {id:string}
export function RecordForm({section,row,employees,terminate,onClose}:{section:Section;row?:Row|undefined;employees:Row[];terminate?:boolean|undefined;onClose:()=>void}){
 const table=sections[section].table as Table;const [busy,setBusy]=useState(false);const [file,setFile]=useState<File>();const [values,setValues]=useState<Record<string,unknown>>({...{dias:table==='ferias'?30:1,salario_base:0,adicionais:0,descontos:0,vale_alimentacao:0,vale_transporte:0,status:table==='ferias'?'pendente':'fechada',tipo:table==='declaracoes'?'vinculo':'outro'},...row});const client=useQueryClient();const save=useServerFn(saveRhRecord);const terminateFn=useServerFn(terminateEmployee);
 const formFields=terminate?[{name:'data_desligamento',label:'Data de desligamento',type:'date',required:true},{name:'motivo_desligamento',label:'Motivo do desligamento',type:'textarea',required:true}]:fields[table];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);let uploaded:string|undefined;try{if(terminate&&row){await terminateFn({data:{id:row['id'],data_desligamento:String(values['data_desligamento']),motivo_desligamento:String(values['motivo_desligamento'])}})}else{
 const payload={...values};if(table==='documentos'&&file){if(file.size>10*1024*1024)throw new Error('O arquivo deve ter no máximo 10 MB.');const {data:userData,error:authError}=await supabase.auth.getUser();if(authError||!userData.user)throw new Error('Entre novamente para anexar o documento.');uploaded=`${userData.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('documentos').upload(uploaded,file);if(error)throw new Error('Não foi possível enviar o arquivo. Tente novamente.');payload['storage_path']=uploaded;payload['tamanho']=file.size;}
 await save({data:{table,...(row?{id:row['id']}:{}),values:payload}});
 }await client.invalidateQueries({queryKey:['rh']});toast.success('Registro salvo com sucesso.');onClose()}catch(err){if(uploaded)await supabase.storage.from('documentos').remove([uploaded]);toast.error(err instanceof Error?err.message:'Não foi possível salvar o registro.')}finally{setBusy(false)}}
 function change(name:string,value:string){setValues(old=>{const next={...old,[name]:value};if(name==='funcionario_id'&&table==='folha_pagamento'){const selected=employees.find(r=>r['id']===value);for(const key of ['salario_base','vale_alimentacao','vale_transporte'])next[key]=selected?.[key]??0}return next})}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="max-h-[90dvh] overflow-y-auto max-w-2xl"><DialogHeader><DialogTitle>{terminate?'Registrar desligamento':row?'Editar registro':table==='documentos'?'Anexar documento':'Novo registro'}</DialogTitle><DialogDescription>{terminate?String(row?.['nome']):sections[section].title}</DialogDescription></DialogHeader><form onSubmit={submit}><div className="form-grid">{formFields.map(f=><label key={f.name} className={`field-label ${f.type==='textarea'?'col-span-full':''}`}>{f.label}{f.required&&<span className="text-primary"> *</span>}{'options' in f && f.options?<select className="form-control" value={String(values[f.name]??f.options[0])} onChange={e=>change(f.name,e.target.value)}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='employee'?<select className="form-control" required value={String(values[f.name]??'')} onChange={e=>change(f.name,e.target.value)}><option value="">Selecionar funcionário</option>{employees.map(r=><option key={r['id']} value={r['id']}>{String(r['nome'])} · {String(r['matricula'])}</option>)}</select>:f.type==='textarea'?<textarea className="form-control min-h-28" required={f.required} value={String(values[f.name]??'')} onChange={e=>change(f.name,e.target.value)}/>:<Input className="mt-2" name={f.name} type={f.type??'text'} required={f.required} min={f.type==='number'?f.name==='dias'?1:0:undefined} step={f.type==='number'?f.name==='dias'?1:0.01:undefined} value={String(values[f.name]??'')} onChange={e=>change(f.name,e.target.value)}/>}</label>)}</div>{table==='documentos'&&!terminate&&<label className="upload-zone mt-5"><Upload/><strong>{file?file.name:'Selecionar arquivo'}</strong><span>PDF, imagens ou documentos · até 10 MB</span><input type="file" required={!row} accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx,.txt,.csv" onChange={e=>setFile(e.target.files?.[0])}/></label>}{table==='folha_pagamento'&&<div className="grid grid-cols-1 gap-2 border-b border-border py-4 text-muted-foreground">Líquido <strong>{money(Number(values['salario_base']||0)+Number(values['adicionais']||0)-Number(values['descontos']||0))}</strong><span>Benefícios {money(benefits({...values,id:row?.id??''}))}</span><span>Total com benefícios {money(Number(values['salario_base']||0)+Number(values['adicionais']||0)-Number(values['descontos']||0)+benefits({...values,id:row?.id??''}))}</span></div>}<div className="mt-7 flex justify-end gap-3"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}><Save/>{busy?'Salvando…':'Salvar registro'}</Button></div></form></DialogContent></Dialog>
}
