import { Link, useNavigate } from '@tanstack/react-router'
import { useQueryClient } from '@tanstack/react-query'
import { Activity, Users, UserMinus, CalendarDays, HeartPulse, FileCheck2, Wallet, FolderOpen, LogOut, Menu, X, Hexagon } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { Button } from '@/components/ui/button'
import { supabase } from '@/integrations/supabase/client'
import { sections, type Section } from './config'
const icons = {painel:Activity,funcionarios:Users,desligados:UserMinus,ferias:CalendarDays,atestados:HeartPulse,declaracoes:FileCheck2,folha:Wallet,documentos:FolderOpen}
export function Brand(){return <div className="flex items-center gap-3"><span className="brand-mark"><Hexagon size={25}/></span><div><span className="brand-name">LIONS<span className="text-primary"> RH</span></span><span className="block font-mono text-[10px] text-muted-foreground">GESTÃO DE PESSOAS</span></div></div>}
export function RhShell({section,counts,children}:{section:Section;counts:Partial<Record<Section,number>>;children:ReactNode}){
 const [open,setOpen]=useState(false);const client=useQueryClient();const navigate=useNavigate();
 async function logout(){await client.cancelQueries();client.clear();await supabase.auth.signOut();await navigate({to:'/auth',replace:true})}
 return <div className="app-shell"><aside className={`app-sidebar ${open?'is-open':''}`}><div className="flex items-center justify-between"><Brand/><Button className="mobile-only" variant="ghost" size="icon" aria-label="Fechar menu" onClick={()=>setOpen(false)}><X/></Button></div><div className="sidebar-label">ESPAÇO DE TRABALHO</div><nav aria-label="Navegação principal">{Object.entries(sections).map(([key,s])=>{const k=key as Section;const Icon=icons[k];return <Link key={k} to={`/${k}`} onClick={()=>setOpen(false)} className={`nav-link ${section===k?'selected':''}`}><Icon size={18}/><span>{k==='painel'?'Visão geral':k==='funcionarios'?'Funcionários ativos':k==='desligados'?'Desligados':s.title}</span>{counts[k]!==undefined&&<span className="nav-count">{counts[k]}</span>}</Link>})}</nav><div className="sidebar-bottom"><div className="flex items-center gap-2 font-mono text-[11px] text-muted-foreground"><span className="status-dot"/> AMBIENTE RH</div><Button onClick={logout} variant="ghost" className="mt-4 w-full justify-start"><LogOut/> Sair da conta</Button></div></aside><div className="app-main"><header className="app-topbar"><div className="flex items-center gap-3"><Button className="mobile-only" variant="ghost" size="icon" aria-label="Abrir menu" onClick={()=>setOpen(true)}><Menu/></Button><span className="text-muted-foreground">Workspace</span><span className="text-muted-foreground">/</span><span>{sections[section].title}</span></div><span className="font-mono text-xs text-muted-foreground">LIONS / PEOPLE</span></header><main className="workspace">{children}</main><footer className="workspace-footer">LIONS RH <span>GESTÃO DE PESSOAS · BRASIL</span></footer></div></div>
}
