/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAtestadosRouteImport } from './routes/_authenticated/atestados'
import { Route as AuthenticatedDeclaracoesRouteImport } from './routes/_authenticated/declaracoes'
import { Route as AuthenticatedDesligadosRouteImport } from './routes/_authenticated/desligados'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedFeriasRouteImport } from './routes/_authenticated/ferias'
import { Route as AuthenticatedFolhaRouteImport } from './routes/_authenticated/folha'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtestadosRoute = AuthenticatedAtestadosRouteImport.update({
  id: '/atestados',
  path: '/atestados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeclaracoesRoute =
  AuthenticatedDeclaracoesRouteImport.update({
    id: '/declaracoes',
    path: '/declaracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesligadosRoute = AuthenticatedDesligadosRouteImport.update({
  id: '/desligados',
  path: '/desligados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeriasRoute = AuthenticatedFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFolhaRoute = AuthenticatedFolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atestados': typeof AuthenticatedAtestadosRoute
  '/declaracoes': typeof AuthenticatedDeclaracoesRoute
  '/desligados': typeof AuthenticatedDesligadosRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ferias': typeof AuthenticatedFeriasRoute
  '/folha': typeof AuthenticatedFolhaRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/painel': typeof AuthenticatedPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atestados': typeof AuthenticatedAtestadosRoute
  '/declaracoes': typeof AuthenticatedDeclaracoesRoute
  '/desligados': typeof AuthenticatedDesligadosRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ferias': typeof AuthenticatedFeriasRoute
  '/folha': typeof AuthenticatedFolhaRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/painel': typeof AuthenticatedPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/atestados': typeof AuthenticatedAtestadosRoute
  '/_authenticated/declaracoes': typeof AuthenticatedDeclaracoesRoute
  '/_authenticated/desligados': typeof AuthenticatedDesligadosRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/ferias': typeof AuthenticatedFeriasRoute
  '/_authenticated/folha': typeof AuthenticatedFolhaRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/atestados'
    | '/declaracoes'
    | '/desligados'
    | '/documentos'
    | '/ferias'
    | '/folha'
    | '/funcionarios'
    | '/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/atestados'
    | '/declaracoes'
    | '/desligados'
    | '/documentos'
    | '/ferias'
    | '/folha'
    | '/funcionarios'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/atestados'
    | '/_authenticated/declaracoes'
    | '/_authenticated/desligados'
    | '/_authenticated/documentos'
    | '/_authenticated/ferias'
    | '/_authenticated/folha'
    | '/_authenticated/funcionarios'
    | '/_authenticated/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atestados': {
      id: '/_authenticated/atestados'
      path: '/atestados'
      fullPath: '/atestados'
      preLoaderRoute: typeof AuthenticatedAtestadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/declaracoes': {
      id: '/_authenticated/declaracoes'
      path: '/declaracoes'
      fullPath: '/declaracoes'
      preLoaderRoute: typeof AuthenticatedDeclaracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desligados': {
      id: '/_authenticated/desligados'
      path: '/desligados'
      fullPath: '/desligados'
      preLoaderRoute: typeof AuthenticatedDesligadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferias': {
      id: '/_authenticated/ferias'
      path: '/ferias'
      fullPath: '/ferias'
      preLoaderRoute: typeof AuthenticatedFeriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folha': {
      id: '/_authenticated/folha'
      path: '/folha'
      fullPath: '/folha'
      preLoaderRoute: typeof AuthenticatedFolhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtestadosRoute: typeof AuthenticatedAtestadosRoute
  AuthenticatedDeclaracoesRoute: typeof AuthenticatedDeclaracoesRoute
  AuthenticatedDesligadosRoute: typeof AuthenticatedDesligadosRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedFeriasRoute: typeof AuthenticatedFeriasRoute
  AuthenticatedFolhaRoute: typeof AuthenticatedFolhaRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtestadosRoute: AuthenticatedAtestadosRoute,
  AuthenticatedDeclaracoesRoute: AuthenticatedDeclaracoesRoute,
  AuthenticatedDesligadosRoute: AuthenticatedDesligadosRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedFeriasRoute: AuthenticatedFeriasRoute,
  AuthenticatedFolhaRoute: AuthenticatedFolhaRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
